config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => 'homes#about'
  get 'searches/search' => 'searches#search', as: 'search'
  devise_for :users
  root to: 'homes#top'
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'users#followings', as: 'followings'
    get 'followers' => 'users#followers', as: 'followers'
  end
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get 'books/sort/:sort', to: 'books#index', as: 'sort_book'
  get 'books/category_search/:category', to: 'books#category_search', as: 'category_search_book'
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @new_book = Book.new
    @comments = BookComment.all
    @book_comment = BookComment.new
  end

  def index
    # ソートリンクをクリックしたときの処理。パラメータが送信されていればソートする。なければ、全てをID順に取得
    if params[:sort].present?
      case params[:sort]
        when "latest"
          @books = Book.all.order(created_at: "DESC")
        when "high_evaluation"
          @books = Book.all.order(evaluation: "DESC")
      end
    else
      @books = Book.all
    end
    @new_book = Book.new
  end

  def category_search
    @books = Book.where(category: params[:category])
    @new_book = Book.new
  end

  def create
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
    if @new_book.save
      redirect_to book_path(@new_book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :category, :evaluation)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    unless @user == current_user
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <%= render 'layouts/errors', obj: @new_book %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
    <%= f.text_field :category, class: 'form-control book_category' %>
  </div>
  <div class = "form-group mb-2" id="evaluate_stars">
    <label>Evaluation</label><br>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

<script>
$('#evaluate_stars').raty({
  starOn: "<%= asset_path('star-on.png') %>",
  starOff: "<%= asset_path('star-off.png') %>",
  starHalf: "<%= asset_path('star-half.png') %>",
  scoreName: 'book[evaluation]' //登録するモデル名とカラム名を記述
});
</script>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td>
          <!--カテゴリーがあれば表示する-->
          <% if book.category.present? %>
            <%= link_to book.category, category_search_book_path(book.category) %>
          <% end %>
        </td>
        <td>
          <!--いいね機能-->
          <div id = "favorite_buttons_<%= book.id %>">
            <%= render "favorites/favorite", book: book %>
          </div>
        </td>
        <td>
          <p><%= book.book_comments.count %>コメント</p>
        </td>
        <td class="book-evaluation" data-score="<%= book.evaluation %>"></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
  $('.book-evaluation').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

app/views/books/category_search.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @new_book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <div  id = "books_index">
        <%= render 'index', books: @books%>
      </div>
    </div>
  </div>
</div>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= form_with model: @book,local:true do |f| %>
        <%= render 'layouts/errors', obj: @book %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control book_title' %>
        </div>
        <div class="form-group">
          <%= f.label :opinion %>
          <%= f.text_area :body, class: 'form-control book_body' %>
        </div>
          <!--評価-->
        <div class="form-group">
          <p class = "text-danger mb-0" style = "font-size: 12px">評価の変更はできません</p>
          <p class="book-evaluation" data-score="<%= @book.evaluation %>"></p>
        </div>
        <div class="form-group">
          <%= f.submit class: 'btn btn-success' %>
        </div>
      <% end %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

<script>
  $('.book-evaluation').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @new_book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= link_to "新しい順", sort_book_path("latest"), remote: true %> <%= " | " %> <%= link_to "評価の高い順", sort_book_path("high_evaluation"), remote: true %>
      <div  id = "books_index">
        <%= render 'index', books: @books%>
      </div>
    </div>
  </div>
</div>

app/views/books/index.js.erb
$('#books_index').html( "<%= j( render 'index', books: @books ) %>" );

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @new_book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td>
            <!--カテゴリーがあれば表示する-->
            <% if @book.category.present? %>
              <%= link_to @book.category, category_search_book_path(@book.category) %>
            <% end %>
          </td>
          <td>
             <!--いいね機能-->
            <div id = "favorite_buttons_<%= @book.id %>">
              <%= render "favorites/favorite", book: @book %>
            </div>
          </td>
          <!--コメント数表示-->
          <td>
          <p><%= @book.book_comments.count %>コメント</p>
          </td>
          <!--評価-->
          <td class="book-evaluation" data-score="<%= @book.evaluation %>"></td>
          <% if @user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>

      <!--コメント欄・リスト-->
      <div class = "comments-box">
        <h3>コメント</h3>
        <!--コメントリスト-->
        <div id = 'book_comments-list'>
          <%= render 'book_comments/book_comments-list' , book: @book %>
        </div>
        <!--コメントフォーム-->
        <div id = "book_comment-form">
          <%= render 'book_comments/book_comment-form', book: @book, book_comment: @book_comment %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $('.book-evaluation').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>